import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <nav className="bg-orange-600 text-white justify-center space-x-4 text-center p-5 gap-5">
            <Link href="/home" className="gap-5 justify-between">
              Home Page
            </Link>
            <Link href="/news" className="gap-6 justify-between  ">
              News page
            </Link>
            <Link href="/aboutus" className="gap-7 justify-between">
              About us
            </Link>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
